version: '3.8'

services:
  # Servicio backend: PHP + Apache
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:80"  # Puerto local 8000 → contenedor puerto 80
    volumes:
      - ./backend:/var/www/html  # Sincroniza archivos PHP
    depends_on:
      - db
    networks:
      - webnet
    env_file:
      - .env  # Lee variables desde el archivo .env

  # Servicio frontend: HTML, JS, CSS con Nginx
  frontend:
    image: nginx:alpine
    ports:
      - "${FRONTEND_PORT}:80"  # Puerto local 8080 → contenedor puerto 80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro  # Monta en modo lectura
    depends_on:
      - backend
    networks:
      - webnet

  # Servicio de base de datos: MySQL
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"  # Puerto por defecto de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - webnet

volumes:
  db_data:  # Volumen persistente para MySQL

networks:
  webnet:   # Red virtual para conectar servicios
